SELECT * FROM customer_behavior.customer_behavior;
select * from customer_behavior.customer_behavior  limit 20;

# --1. What is the total revenue generated by male vs. female customer?

SELECT `Customer Id`, SUM(`Purchase Amount`) AS revenue
FROM customer_behavior
GROUP BY `Customer Id`;

-- 2 Which customer used a discount but still more than the average purchase amount ?

SELECT `Customer Id`, `Purchase Amount`
FROM customer_behavior
WHERE `Previous Purchases` = 'Yes'
AND `Purchase Amount` >= (
    SELECT AVG(`Purchase Amount`)
    FROM customer_behavior
    
);


-- 3 hich are the top 5 product with hieght average review rating

SELECT 
    `Item Purchased`,
    ROUND(AVG(`Review Rating`), 2) AS `Average Review Rating`
FROM 
    customer_behavior
GROUP BY 
    `Item Purchased`
ORDER BY 
    AVG(`Review Rating`) DESC
LIMIT 5;

-- 04 . compare the average purchase amount between standard and express shipping

select `Shipping Type`,
ROUND(AVG(`Purchase Amount`),2)
from customer_behavior
where `Shipping Type` in ('Standard', 'Express')
group by `Shipping Type`;

#-- 05 . Do subscribed customer spend more? 
#-- compare average spend and total revenue between subscribe and non-subscribe. 

select `Subscription`,
COUNT(`Customer Id`) as  `total_customer`,
ROUND(AVG(`Purchase Amount`),2) as avg_spend,
ROUND(SUM(`Purchase Amount`),2) as total_revenue
from customer_behavior
group by `Subscription` 
order by total_revenue , avg_spend desc;

-- 06. Which 5 product have the highest percentage of purchase with discount applied?

-- If the column name is 'Discount'
SELECT 
    `Item Purchased`,
    ROUND(
        100 * SUM(CASE WHEN `Discount Promo Code` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM customer_behavior
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;


-- 7. Segment customers into new, returning, and loyal based on their total
-- number of previous purchase, and show the count of each segment ,

WITH `Shipping Type` AS (
    SELECT 
        `Customer Id`,
        `Previous Purchases`,
        CASE 
            WHEN `Previous Purchases` = 1 THEN 'New'
            WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_behavior
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM `Shipping Type`
GROUP BY customer_segment;




